### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins

### ISSUE THREAD

**Issue by SooditK** [mattddean/t3-app-router-edge-drizzle#4]
After following the steps in `README.md`
When I did `pnpm run dev`, It showed the following error

![image](https://user-images.githubusercontent.com/50576944/232003345-f2b4a7bb-c161-4582-8075-b8109cef2bd7.png)

> `pnpm drizle-kit push:mysql` was successful and I got `[✓] Changes applied`

I tried building the application with `pnpm run build` and It also failed with the error:

```Failed to compile.

node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:28:395974
    at Hook.eval [as callAsync] (eval at create (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
    at Object.processResource (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:28:395899)
    at processResource (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4667)
    at runLoaders (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8590)
    at NormalModule._doBuild (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:28:395761)
    at NormalModule.build (/home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:28:397789)
    at /home/soodit/Documents/dev/oren/oren-clone/drijjle/node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/webpack/bundle5.js:28:81243

Import trace for requested module:
node:crypto
./node_modules/.pnpm/@noble+hashes@1.3.0/node_modules/@noble/hashes/esm/cryptoNode.js
./node_modules/.pnpm/@noble+hashes@1.3.0/node_modules/@noble/hashes/esm/utils.js
./node_modules/.pnpm/@noble+hashes@1.3.0/node_modules/@noble/hashes/esm/sha3.js
./node_modules/.pnpm/@paralleldrive+cuid2@2.2.0/node_modules/@paralleldrive/cuid2/src/index.js
./node_modules/.pnpm/@paralleldrive+cuid2@2.2.0/node_modules/@paralleldrive/cuid2/index.js
./src/auth/adapters/drizzle-orm.ts
./src/auth/options.ts
./src/app/api/auth/[...nextauth]/route.ts
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute&page=%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute&pagePath=private-next-app-dir%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute.ts&appDir=%2Fhome%2Fsoodit%2FDocuments%2Fdev%2Foren%2Foren-clone%2Fdrijjle%2Fsrc%2Fapp&appPaths=%2Fapi%2Fauth%2F%5B...nextauth%5D%2Froute&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&assetPrefix=&nextConfigOutput=!./src/app/api/auth/[...nextauth]/route.ts?__edge_ssr_entry__


Build failed because of webpack errors
info  - Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.

**Comment by mattddean** [comment]
What version of pnpm and node are you using?

I'm not seeing this issue with these versions:

```sh
❯ pnpm -v
8.1.1
❯ node -v
v18.12.1
```

**Comment by SooditK** [comment]
```
❯ pnpm -v
8.2.0
❯ node -v
v18.15.0
❯ npm -v
v9.5.0
❯ yarn -v
v1.22.19
```

**Comment by mattddean** [comment]
I've updated to these versions and cannot reproduce this issue. Are you able to reproduce it in a StackBlitz?

**Comment by SooditK** [comment]
Interestingly, StackBlitz produced a different error:

![image](https://user-images.githubusercontent.com/50576944/233240928-0b8b3d40-1f03-4900-a135-a96a9a4bb6ea.png)

![image](https://user-images.githubusercontent.com/50576944/233241093-afa77647-42f3-4680-b016-dca84b467ed7.png)

```
error - Error [TypeError]: runtime.context.addEventListener is not a function
    at createModuleContext (file:///home/projects/nbwivyklk.github/node_modules/.pnpm/next@13.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/context.js:314:21)
```

**Comment by miguelangelrm** [comment]
Hi,

The issue comes from the library `@paralleldrive/cuid2`. There's no native polyfill for crypto on edge runtime afaik.

**Comment by mattddean** [comment]
@miguelangelrm you're right. https://twitter.com/t3dotgg/status/1650363208501452802?s=46&t=gcUfMBapkwWetwiN_HjdZw
While it seems to build for me personally, I think I'm going to switch to a cuid v1 package until the bundling polyfill kinks get worked out in the App Router.

**Comment by mattddean** [comment]
@SooditK let me know if this problem is fixed for you

**Comment by teovillanueva** [comment]
Hello, I fixed this with this patch-package diff.

`patches/@noble+hashes+1.3.0.patch`

```
diff --git a/node_modules/@noble/hashes/cryptoNode.js b/node_modules/@noble/hashes/cryptoNode.js
index 939525d..3038d91 100644
--- a/node_modules/@noble/hashes/cryptoNode.js
+++ b/node_modules/@noble/hashes/cryptoNode.js
@@ -1,6 +1,5 @@
 "use strict";
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.crypto = void 0;
-const nc = require("node:crypto");
-exports.crypto = nc && typeof nc === 'object' && 'webcrypto' in nc ? nc.webcrypto : undefined;
+exports.crypto = typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
 //# sourceMappingURL=cryptoNode.js.map
\ No newline at end of file
diff --git a/node_modules/@noble/hashes/esm/cryptoNode.js b/node_modules/@noble/hashes/esm/cryptoNode.js
index 4bac77a..a0dac2b 100644
--- a/node_modules/@noble/hashes/esm/cryptoNode.js
+++ b/node_modules/@noble/hashes/esm/cryptoNode.js
@@ -1,3 +1,2 @@
-import * as nc from 'node:crypto';
-export const crypto = nc && typeof nc === 'object' && 'webcrypto' in nc ? nc.webcrypto : undefined;
+export const crypto = typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
 //# sourceMappingURL=cryptoNode.js.map
\ No newline at end of file
diff --git a/node_modules/@noble/hashes/src/cryptoNode.ts b/node_modules/@noble/hashes/src/cryptoNode.ts
index 65d0853..9732af4 100644
--- a/node_modules/@noble/hashes/src/cryptoNode.ts
+++ b/node_modules/@noble/hashes/src/cryptoNode.ts
@@ -1,3 +1,3 @@
-import * as nc from 'node:crypto';
+declare const globalThis: Record<string, any> | undefined;
 export const crypto =
-  nc && typeof nc === 'object' && 'webcrypto' in nc ? (nc.webcrypto as any) : undefined;
+  typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
```

**Comment by mattddean** [comment]
@SooditK can you verify whether or not @teovillanueva's fix solves the problem for you? It's merged to main.
